name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip curl python3 python3-pip

      - name: Install Android SDK + Build Tools
        run: |
          # Create SDK directory
          mkdir -p $HOME/android-sdk
          export ANDROID_SDK_ROOT=$HOME/android-sdk

          # Download command line tools
          curl -fo sdk-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip sdk-tools.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest

          # Accept licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk --licenses

          # Install ALL required Android tools
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/android-sdk \
            "platform-tools" \
            "platforms;android-34" \
            "platforms;android-33" \
            "platforms;android-32" \
            "platforms;android-31" \
            "build-tools;34.0.0" \
            "build-tools;33.0.2" \
            "build-tools;32.0.0" \
            "build-tools;31.0.0" \
            "ndk;25.1.8937393" \
            "ndk;21.4.7075529" \
            "cmake;3.22.1" \
            "cmake;3.10.2.4988404"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer android debug

        env:
          ANDROID_HOME: $HOME/android-sdk
          ANDROID_SDK_ROOT: $HOME/android-sdk
