name: Build APK from Kivy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y git build-essential libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-11-jdk
          pip install --upgrade pip
          pip install buildozer cython
          
      - name: Install Android SDK components
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-33"
          sdkmanager "build-tools;33.0.2"
          sdkmanager "platforms;android-32"
          sdkmanager "build-tools;32.0.0"
          sdkmanager "platforms;android-31"
          sdkmanager "build-tools;31.0.0"
          sdkmanager "platforms;android-30"
          sdkmanager "build-tools;30.0.3"
          sdkmanager "ndk;21.4.7075529"
          sdkmanager "cmake;3.10.2.4988404"

      - name: Build APK
        run: | 
         buildozer android debug

      - name: Upload APK
        uses: 'actions/checkout@v3'
        
        with:
          name: kivy-apk
          path: bin/*.apk
