name: Build APK from Kivy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install basic dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y unzip git curl openjdk-11-jdk build-essential

      - name: Install dependencies
        run: |
          sudo apt install -y git build-essential libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-11-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK and dependencies
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-34"

      - name: Verify installation
        run: |
          echo "Android SDK installed successfully!"
          ls $ANDROID_HOME/platform-tools
          ls $ANDROID_HOME/build-tools/34.0.0
          ls $ANDROID_HOME/platforms/android-34
          

      - name: Verify AIDL
        run: |
          export ANDROID_HOME=/usr/lib/android-sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses:  'actions/checkout@v3'
        with:
          name: kivy-apk
          path: bin/*.apk
