name: Build APK from Kivy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip zip unzip openjdk-11-jdk
          sudo apt install -y git build-essential libncurses5 libffi-dev libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev
          pip install --upgrade pip
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
          
          
          - الاسم: إعداد بيئة Node.js
  الاستخدامات: actions/setup-node@v3.9.0
  مع:
    # تعيين دائمًا المصادقة في npmrc.
    always-auth: # اختياري، الافتراضي هو false
    # مواصفات الإصدار المُراد استخدامه. أمثلة: 12.x، 10.15.1، >=10.15.0.
    إصدار العقدة: # اختياري
    # ملف يحتوي على مواصفات الإصدار المُراد استخدامه. أمثلة: .nvmrc، .node-version، .tool-versions.
    ملف إصدار العقدة: # اختياري
    # بنية النظام المستهدفة التي ستستخدمها العقدة. أمثلة: x86، x64. سيتم استخدام بنية النظام افتراضيًا.
    الهندسة المعمارية: # اختياري
    # قم بتعيين هذا الخيار إذا كنت تريد أن يتحقق الإجراء من أحدث إصدار متاح يلبي مواصفات الإصدار.
    التحقق الأحدث: # اختياري
    # سجل اختياري لإعداد المصادقة. سيُضبط السجل في ملفي .npmrc و.yarnrc على مستوى المشروع، ويُعدّ المصادقة للقراءة من env.NODE_AUTH_TOKEN.
    عنوان URL للتسجيل: # اختياري
    # نطاق اختياري للمصادقة على السجلات المحددة. سيعود الأمر إلى مالك المستودع عند استخدام سجل حزم GitHub (https://npm.pkg.github.com/).
    النطاق: # اختياري
    # يُستخدم لسحب توزيعات العقد من إصدارات العقد. نظرًا لوجود قيمة افتراضية، لا يُوفّرها المستخدم عادةً. عند تشغيل هذا الإجراء على github.com، تكون القيمة الافتراضية كافية. عند التشغيل على GHES، يمكنك تمرير رمز وصول شخصي إلى github.com إذا كنت تواجه قيودًا على السرعة.
    الرمز المميز: # اختياري، الافتراضي هو ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # يُستخدم لتحديد مدير حزم للتخزين المؤقت في الدليل الافتراضي. القيم المدعومة: npm، yarn، pnpm.
    ذاكرة التخزين المؤقت: # اختياري
    # يستخدم لتحديد المسار إلى ملف التبعيات: package-lock.json، yarn.lock، وما إلى ذلك. يدعم الأحرف البدل أو قائمة بأسماء الملفات لتخزين التبعيات المتعددة مؤقتًا.
    مسار تبعية ذاكرة التخزين المؤقت: # اختياري
          
