name: Build APK from Kivy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install basic dependencies
        run: |
          sudo apt update && sudo apt upgrade -y
          sudo apt install -y unzip git curl openjdk-11-jdk build-essential

      - name: Install Python dependencies
        run: |
          sudo apt install -y python3-pip zip unzip
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -o commandlinetools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest || true
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-34" "tools"

      - name: Install Missing AIDL
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager "platform-tools" "build-tools;36.0.0" "platforms;android-34"

      - name: Verify AIDL
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          if ! command -v aidl >/dev/null; then
            echo "aidl not found, installation failed. Exiting."
            exit 1
          fi

      - name: Build APK
        run: |
          buildozer android debug
